name = "MTTS"
author = "MTR Technology & Transport Server"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9dbe18fc3f7162da160a20ac16e3f61b93f55bd2faaf845d99c06302887133fb"

[versions]
fabric = "0.18.4"
minecraft = "1.19.2"
