name = "MTTS"
author = "MTR Technology & Transport Server"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ab0750feb12083b55196db560d02c76ca9b1d80a61d855f759ee21d0b960ac8"

[versions]
fabric = "0.19.3"
minecraft = "1.19.2"
