name = "MTTS"
author = "MTR Technology & Transport Server"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e55734efeaf7082f2c06d9f7723b69b1d141604ed99a75b0e7a69dc3f95de630"

[versions]
fabric = "0.19.2"
minecraft = "1.19.2"
