name = "MTTS"
author = "MTR Technology & Transport Server"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a4afafaf27787d7d489e8ec29524c4d7e9e56d5f0beb646cbd59a1329848e1d"

[versions]
fabric = "0.18.4"
minecraft = "1.19.2"
