name = "MTTS"
author = "MTR Technology & Transport Server"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "211825729a2d362a711188208d6dab9659160e3bd7c5fe6a4b6669b17cdbf1d4"

[versions]
fabric = "0.19.3"
minecraft = "1.19.2"
