name = "MTTS"
author = "MTR Technology & Transport Server"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "740e566f5b5232efe1e8a1ea587915af60f65ab260b3eefb7344b9cc001e4702"

[versions]
fabric = "0.18.4"
minecraft = "1.19.2"
