name = "MTTS"
author = "MTR Technology & Transport Server"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a9d49592a5263c06d8f396e10c000e09030bf52245851531a180ca5f926a4b5"

[versions]
fabric = "0.19.2"
minecraft = "1.19.2"
